// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package timescale_repository

import (
	"context"

	"github.com/bismastr/cs-price-alert/internal/timescale_repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CountSearchPriceChangesByName provides a mock function for the type MockRepository
func (_mock *MockRepository) CountSearchPriceChangesByName(ctx context.Context, query string) (int64, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for CountSearchPriceChangesByName")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, query)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CountSearchPriceChangesByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountSearchPriceChangesByName'
type MockRepository_CountSearchPriceChangesByName_Call struct {
	*mock.Call
}

// CountSearchPriceChangesByName is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
func (_e *MockRepository_Expecter) CountSearchPriceChangesByName(ctx interface{}, query interface{}) *MockRepository_CountSearchPriceChangesByName_Call {
	return &MockRepository_CountSearchPriceChangesByName_Call{Call: _e.mock.On("CountSearchPriceChangesByName", ctx, query)}
}

func (_c *MockRepository_CountSearchPriceChangesByName_Call) Run(run func(ctx context.Context, query string)) *MockRepository_CountSearchPriceChangesByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CountSearchPriceChangesByName_Call) Return(n int64, err error) *MockRepository_CountSearchPriceChangesByName_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepository_CountSearchPriceChangesByName_Call) RunAndReturn(run func(ctx context.Context, query string) (int64, error)) *MockRepository_CountSearchPriceChangesByName_Call {
	_c.Call.Return(run)
	return _c
}

// Get24HourPricesChanges provides a mock function for the type MockRepository
func (_mock *MockRepository) Get24HourPricesChanges(ctx context.Context) ([]timescale_repository.Get24HourPricesChangesRow, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Get24HourPricesChanges")
	}

	var r0 []timescale_repository.Get24HourPricesChangesRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]timescale_repository.Get24HourPricesChangesRow, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []timescale_repository.Get24HourPricesChangesRow); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]timescale_repository.Get24HourPricesChangesRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Get24HourPricesChanges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get24HourPricesChanges'
type MockRepository_Get24HourPricesChanges_Call struct {
	*mock.Call
}

// Get24HourPricesChanges is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) Get24HourPricesChanges(ctx interface{}) *MockRepository_Get24HourPricesChanges_Call {
	return &MockRepository_Get24HourPricesChanges_Call{Call: _e.mock.On("Get24HourPricesChanges", ctx)}
}

func (_c *MockRepository_Get24HourPricesChanges_Call) Run(run func(ctx context.Context)) *MockRepository_Get24HourPricesChanges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_Get24HourPricesChanges_Call) Return(get24HourPricesChangesRows []timescale_repository.Get24HourPricesChangesRow, err error) *MockRepository_Get24HourPricesChanges_Call {
	_c.Call.Return(get24HourPricesChangesRows, err)
	return _c
}

func (_c *MockRepository_Get24HourPricesChanges_Call) RunAndReturn(run func(ctx context.Context) ([]timescale_repository.Get24HourPricesChangesRow, error)) *MockRepository_Get24HourPricesChanges_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllPriceChanges provides a mock function for the type MockRepository
func (_mock *MockRepository) GetAllPriceChanges(ctx context.Context, arg timescale_repository.GetAllPriceChangesParams) ([]timescale_repository.GetAllPriceChangesRow, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetAllPriceChanges")
	}

	var r0 []timescale_repository.GetAllPriceChangesRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, timescale_repository.GetAllPriceChangesParams) ([]timescale_repository.GetAllPriceChangesRow, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, timescale_repository.GetAllPriceChangesParams) []timescale_repository.GetAllPriceChangesRow); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]timescale_repository.GetAllPriceChangesRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, timescale_repository.GetAllPriceChangesParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetAllPriceChanges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllPriceChanges'
type MockRepository_GetAllPriceChanges_Call struct {
	*mock.Call
}

// GetAllPriceChanges is a helper method to define mock.On call
//   - ctx context.Context
//   - arg timescale_repository.GetAllPriceChangesParams
func (_e *MockRepository_Expecter) GetAllPriceChanges(ctx interface{}, arg interface{}) *MockRepository_GetAllPriceChanges_Call {
	return &MockRepository_GetAllPriceChanges_Call{Call: _e.mock.On("GetAllPriceChanges", ctx, arg)}
}

func (_c *MockRepository_GetAllPriceChanges_Call) Run(run func(ctx context.Context, arg timescale_repository.GetAllPriceChangesParams)) *MockRepository_GetAllPriceChanges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 timescale_repository.GetAllPriceChangesParams
		if args[1] != nil {
			arg1 = args[1].(timescale_repository.GetAllPriceChangesParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetAllPriceChanges_Call) Return(getAllPriceChangesRows []timescale_repository.GetAllPriceChangesRow, err error) *MockRepository_GetAllPriceChanges_Call {
	_c.Call.Return(getAllPriceChangesRows, err)
	return _c
}

func (_c *MockRepository_GetAllPriceChanges_Call) RunAndReturn(run func(ctx context.Context, arg timescale_repository.GetAllPriceChangesParams) ([]timescale_repository.GetAllPriceChangesRow, error)) *MockRepository_GetAllPriceChanges_Call {
	_c.Call.Return(run)
	return _c
}

// GetItemPriceChartByDay provides a mock function for the type MockRepository
func (_mock *MockRepository) GetItemPriceChartByDay(ctx context.Context, params timescale_repository.GetItemPriceChartByDayParams) ([]timescale_repository.GetItemPriceChartByDayRow, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetItemPriceChartByDay")
	}

	var r0 []timescale_repository.GetItemPriceChartByDayRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, timescale_repository.GetItemPriceChartByDayParams) ([]timescale_repository.GetItemPriceChartByDayRow, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, timescale_repository.GetItemPriceChartByDayParams) []timescale_repository.GetItemPriceChartByDayRow); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]timescale_repository.GetItemPriceChartByDayRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, timescale_repository.GetItemPriceChartByDayParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetItemPriceChartByDay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItemPriceChartByDay'
type MockRepository_GetItemPriceChartByDay_Call struct {
	*mock.Call
}

// GetItemPriceChartByDay is a helper method to define mock.On call
//   - ctx context.Context
//   - params timescale_repository.GetItemPriceChartByDayParams
func (_e *MockRepository_Expecter) GetItemPriceChartByDay(ctx interface{}, params interface{}) *MockRepository_GetItemPriceChartByDay_Call {
	return &MockRepository_GetItemPriceChartByDay_Call{Call: _e.mock.On("GetItemPriceChartByDay", ctx, params)}
}

func (_c *MockRepository_GetItemPriceChartByDay_Call) Run(run func(ctx context.Context, params timescale_repository.GetItemPriceChartByDayParams)) *MockRepository_GetItemPriceChartByDay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 timescale_repository.GetItemPriceChartByDayParams
		if args[1] != nil {
			arg1 = args[1].(timescale_repository.GetItemPriceChartByDayParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetItemPriceChartByDay_Call) Return(getItemPriceChartByDayRows []timescale_repository.GetItemPriceChartByDayRow, err error) *MockRepository_GetItemPriceChartByDay_Call {
	_c.Call.Return(getItemPriceChartByDayRows, err)
	return _c
}

func (_c *MockRepository_GetItemPriceChartByDay_Call) RunAndReturn(run func(ctx context.Context, params timescale_repository.GetItemPriceChartByDayParams) ([]timescale_repository.GetItemPriceChartByDayRow, error)) *MockRepository_GetItemPriceChartByDay_Call {
	_c.Call.Return(run)
	return _c
}

// GetItemPriceChartByHour provides a mock function for the type MockRepository
func (_mock *MockRepository) GetItemPriceChartByHour(ctx context.Context, params timescale_repository.GetItemPriceChartByHourParams) ([]timescale_repository.GetItemPriceChartByHourRow, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetItemPriceChartByHour")
	}

	var r0 []timescale_repository.GetItemPriceChartByHourRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, timescale_repository.GetItemPriceChartByHourParams) ([]timescale_repository.GetItemPriceChartByHourRow, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, timescale_repository.GetItemPriceChartByHourParams) []timescale_repository.GetItemPriceChartByHourRow); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]timescale_repository.GetItemPriceChartByHourRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, timescale_repository.GetItemPriceChartByHourParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetItemPriceChartByHour_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItemPriceChartByHour'
type MockRepository_GetItemPriceChartByHour_Call struct {
	*mock.Call
}

// GetItemPriceChartByHour is a helper method to define mock.On call
//   - ctx context.Context
//   - params timescale_repository.GetItemPriceChartByHourParams
func (_e *MockRepository_Expecter) GetItemPriceChartByHour(ctx interface{}, params interface{}) *MockRepository_GetItemPriceChartByHour_Call {
	return &MockRepository_GetItemPriceChartByHour_Call{Call: _e.mock.On("GetItemPriceChartByHour", ctx, params)}
}

func (_c *MockRepository_GetItemPriceChartByHour_Call) Run(run func(ctx context.Context, params timescale_repository.GetItemPriceChartByHourParams)) *MockRepository_GetItemPriceChartByHour_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 timescale_repository.GetItemPriceChartByHourParams
		if args[1] != nil {
			arg1 = args[1].(timescale_repository.GetItemPriceChartByHourParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetItemPriceChartByHour_Call) Return(getItemPriceChartByHourRows []timescale_repository.GetItemPriceChartByHourRow, err error) *MockRepository_GetItemPriceChartByHour_Call {
	_c.Call.Return(getItemPriceChartByHourRows, err)
	return _c
}

func (_c *MockRepository_GetItemPriceChartByHour_Call) RunAndReturn(run func(ctx context.Context, params timescale_repository.GetItemPriceChartByHourParams) ([]timescale_repository.GetItemPriceChartByHourRow, error)) *MockRepository_GetItemPriceChartByHour_Call {
	_c.Call.Return(run)
	return _c
}

// GetItemSparklineWeekly provides a mock function for the type MockRepository
func (_mock *MockRepository) GetItemSparklineWeekly(ctx context.Context, itemID []int32) ([]timescale_repository.GetItemSparklineWeeklyRow, error) {
	ret := _mock.Called(ctx, itemID)

	if len(ret) == 0 {
		panic("no return value specified for GetItemSparklineWeekly")
	}

	var r0 []timescale_repository.GetItemSparklineWeeklyRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int32) ([]timescale_repository.GetItemSparklineWeeklyRow, error)); ok {
		return returnFunc(ctx, itemID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int32) []timescale_repository.GetItemSparklineWeeklyRow); ok {
		r0 = returnFunc(ctx, itemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]timescale_repository.GetItemSparklineWeeklyRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []int32) error); ok {
		r1 = returnFunc(ctx, itemID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetItemSparklineWeekly_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItemSparklineWeekly'
type MockRepository_GetItemSparklineWeekly_Call struct {
	*mock.Call
}

// GetItemSparklineWeekly is a helper method to define mock.On call
//   - ctx context.Context
//   - itemID []int32
func (_e *MockRepository_Expecter) GetItemSparklineWeekly(ctx interface{}, itemID interface{}) *MockRepository_GetItemSparklineWeekly_Call {
	return &MockRepository_GetItemSparklineWeekly_Call{Call: _e.mock.On("GetItemSparklineWeekly", ctx, itemID)}
}

func (_c *MockRepository_GetItemSparklineWeekly_Call) Run(run func(ctx context.Context, itemID []int32)) *MockRepository_GetItemSparklineWeekly_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int32
		if args[1] != nil {
			arg1 = args[1].([]int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetItemSparklineWeekly_Call) Return(getItemSparklineWeeklyRows []timescale_repository.GetItemSparklineWeeklyRow, err error) *MockRepository_GetItemSparklineWeekly_Call {
	_c.Call.Return(getItemSparklineWeeklyRows, err)
	return _c
}

func (_c *MockRepository_GetItemSparklineWeekly_Call) RunAndReturn(run func(ctx context.Context, itemID []int32) ([]timescale_repository.GetItemSparklineWeeklyRow, error)) *MockRepository_GetItemSparklineWeekly_Call {
	_c.Call.Return(run)
	return _c
}

// GetPriceChangesByItemIDs provides a mock function for the type MockRepository
func (_mock *MockRepository) GetPriceChangesByItemIDs(ctx context.Context, arg timescale_repository.GetPriceChangesByItemIDsParams) ([]timescale_repository.GetPriceChangesByItemIDsRow, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetPriceChangesByItemIDs")
	}

	var r0 []timescale_repository.GetPriceChangesByItemIDsRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, timescale_repository.GetPriceChangesByItemIDsParams) ([]timescale_repository.GetPriceChangesByItemIDsRow, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, timescale_repository.GetPriceChangesByItemIDsParams) []timescale_repository.GetPriceChangesByItemIDsRow); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]timescale_repository.GetPriceChangesByItemIDsRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, timescale_repository.GetPriceChangesByItemIDsParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetPriceChangesByItemIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPriceChangesByItemIDs'
type MockRepository_GetPriceChangesByItemIDs_Call struct {
	*mock.Call
}

// GetPriceChangesByItemIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - arg timescale_repository.GetPriceChangesByItemIDsParams
func (_e *MockRepository_Expecter) GetPriceChangesByItemIDs(ctx interface{}, arg interface{}) *MockRepository_GetPriceChangesByItemIDs_Call {
	return &MockRepository_GetPriceChangesByItemIDs_Call{Call: _e.mock.On("GetPriceChangesByItemIDs", ctx, arg)}
}

func (_c *MockRepository_GetPriceChangesByItemIDs_Call) Run(run func(ctx context.Context, arg timescale_repository.GetPriceChangesByItemIDsParams)) *MockRepository_GetPriceChangesByItemIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 timescale_repository.GetPriceChangesByItemIDsParams
		if args[1] != nil {
			arg1 = args[1].(timescale_repository.GetPriceChangesByItemIDsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetPriceChangesByItemIDs_Call) Return(getPriceChangesByItemIDsRows []timescale_repository.GetPriceChangesByItemIDsRow, err error) *MockRepository_GetPriceChangesByItemIDs_Call {
	_c.Call.Return(getPriceChangesByItemIDsRows, err)
	return _c
}

func (_c *MockRepository_GetPriceChangesByItemIDs_Call) RunAndReturn(run func(ctx context.Context, arg timescale_repository.GetPriceChangesByItemIDsParams) ([]timescale_repository.GetPriceChangesByItemIDsRow, error)) *MockRepository_GetPriceChangesByItemIDs_Call {
	_c.Call.Return(run)
	return _c
}

// InsertPrice provides a mock function for the type MockRepository
func (_mock *MockRepository) InsertPrice(ctx context.Context, params timescale_repository.InsertPriceParams) error {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for InsertPrice")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, timescale_repository.InsertPriceParams) error); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_InsertPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertPrice'
type MockRepository_InsertPrice_Call struct {
	*mock.Call
}

// InsertPrice is a helper method to define mock.On call
//   - ctx context.Context
//   - params timescale_repository.InsertPriceParams
func (_e *MockRepository_Expecter) InsertPrice(ctx interface{}, params interface{}) *MockRepository_InsertPrice_Call {
	return &MockRepository_InsertPrice_Call{Call: _e.mock.On("InsertPrice", ctx, params)}
}

func (_c *MockRepository_InsertPrice_Call) Run(run func(ctx context.Context, params timescale_repository.InsertPriceParams)) *MockRepository_InsertPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 timescale_repository.InsertPriceParams
		if args[1] != nil {
			arg1 = args[1].(timescale_repository.InsertPriceParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_InsertPrice_Call) Return(err error) *MockRepository_InsertPrice_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_InsertPrice_Call) RunAndReturn(run func(ctx context.Context, params timescale_repository.InsertPriceParams) error) *MockRepository_InsertPrice_Call {
	_c.Call.Return(run)
	return _c
}

// SearchPriceChangesByName provides a mock function for the type MockRepository
func (_mock *MockRepository) SearchPriceChangesByName(ctx context.Context, arg timescale_repository.SearchPriceChangesByNameParams) ([]timescale_repository.SearchPriceChangesByNameRow, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for SearchPriceChangesByName")
	}

	var r0 []timescale_repository.SearchPriceChangesByNameRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, timescale_repository.SearchPriceChangesByNameParams) ([]timescale_repository.SearchPriceChangesByNameRow, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, timescale_repository.SearchPriceChangesByNameParams) []timescale_repository.SearchPriceChangesByNameRow); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]timescale_repository.SearchPriceChangesByNameRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, timescale_repository.SearchPriceChangesByNameParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_SearchPriceChangesByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchPriceChangesByName'
type MockRepository_SearchPriceChangesByName_Call struct {
	*mock.Call
}

// SearchPriceChangesByName is a helper method to define mock.On call
//   - ctx context.Context
//   - arg timescale_repository.SearchPriceChangesByNameParams
func (_e *MockRepository_Expecter) SearchPriceChangesByName(ctx interface{}, arg interface{}) *MockRepository_SearchPriceChangesByName_Call {
	return &MockRepository_SearchPriceChangesByName_Call{Call: _e.mock.On("SearchPriceChangesByName", ctx, arg)}
}

func (_c *MockRepository_SearchPriceChangesByName_Call) Run(run func(ctx context.Context, arg timescale_repository.SearchPriceChangesByNameParams)) *MockRepository_SearchPriceChangesByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 timescale_repository.SearchPriceChangesByNameParams
		if args[1] != nil {
			arg1 = args[1].(timescale_repository.SearchPriceChangesByNameParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_SearchPriceChangesByName_Call) Return(searchPriceChangesByNameRows []timescale_repository.SearchPriceChangesByNameRow, err error) *MockRepository_SearchPriceChangesByName_Call {
	_c.Call.Return(searchPriceChangesByNameRows, err)
	return _c
}

func (_c *MockRepository_SearchPriceChangesByName_Call) RunAndReturn(run func(ctx context.Context, arg timescale_repository.SearchPriceChangesByNameParams) ([]timescale_repository.SearchPriceChangesByNameRow, error)) *MockRepository_SearchPriceChangesByName_Call {
	_c.Call.Return(run)
	return _c
}
