version: '3.8'

services:
  scrape-cs-items:
    build:
      context: .
      target: scrape-cs-items # Matches Dockerfile target
    env_file:
      - .env # Environment variables (e.g., API keys)
    restart: unless_stopped

  alerts:
    build:
      context: .
      target: alerts
    env_file:
      - .env
    depends_on:
      - scrape-cs-items # Optional: Wait for scraper to start
    restart: unless_stopped
