version: '3.8'

services:
  scrape-cs-items:
    build:
      context: .
      target: scrape-cs-items
    env_file:
      - .env

  alerts:
    build:
      context: .
      target: alerts
    env_file:
      - .env
    depends_on:
      - scrape-cs-items
