// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"

	"github.com/bismastr/cs-price-alert/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateItem provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateItem(ctx context.Context, arg repository.CreateItemParams) (repository.Item, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateItem")
	}

	var r0 repository.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.CreateItemParams) (repository.Item, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.CreateItemParams) repository.Item); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(repository.Item)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.CreateItemParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CreateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateItem'
type MockRepository_CreateItem_Call struct {
	*mock.Call
}

// CreateItem is a helper method to define mock.On call
//   - ctx context.Context
//   - arg repository.CreateItemParams
func (_e *MockRepository_Expecter) CreateItem(ctx interface{}, arg interface{}) *MockRepository_CreateItem_Call {
	return &MockRepository_CreateItem_Call{Call: _e.mock.On("CreateItem", ctx, arg)}
}

func (_c *MockRepository_CreateItem_Call) Run(run func(ctx context.Context, arg repository.CreateItemParams)) *MockRepository_CreateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.CreateItemParams
		if args[1] != nil {
			arg1 = args[1].(repository.CreateItemParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateItem_Call) Return(item repository.Item, err error) *MockRepository_CreateItem_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockRepository_CreateItem_Call) RunAndReturn(run func(ctx context.Context, arg repository.CreateItemParams) (repository.Item, error)) *MockRepository_CreateItem_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllItemsCount provides a mock function for the type MockRepository
func (_mock *MockRepository) GetAllItemsCount(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllItemsCount")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetAllItemsCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllItemsCount'
type MockRepository_GetAllItemsCount_Call struct {
	*mock.Call
}

// GetAllItemsCount is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) GetAllItemsCount(ctx interface{}) *MockRepository_GetAllItemsCount_Call {
	return &MockRepository_GetAllItemsCount_Call{Call: _e.mock.On("GetAllItemsCount", ctx)}
}

func (_c *MockRepository_GetAllItemsCount_Call) Run(run func(ctx context.Context)) *MockRepository_GetAllItemsCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_GetAllItemsCount_Call) Return(n int64, err error) *MockRepository_GetAllItemsCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepository_GetAllItemsCount_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockRepository_GetAllItemsCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetItemByHashName provides a mock function for the type MockRepository
func (_mock *MockRepository) GetItemByHashName(ctx context.Context, hashName string) (repository.GetItemByHashNameRow, error) {
	ret := _mock.Called(ctx, hashName)

	if len(ret) == 0 {
		panic("no return value specified for GetItemByHashName")
	}

	var r0 repository.GetItemByHashNameRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (repository.GetItemByHashNameRow, error)); ok {
		return returnFunc(ctx, hashName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) repository.GetItemByHashNameRow); ok {
		r0 = returnFunc(ctx, hashName)
	} else {
		r0 = ret.Get(0).(repository.GetItemByHashNameRow)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, hashName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetItemByHashName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItemByHashName'
type MockRepository_GetItemByHashName_Call struct {
	*mock.Call
}

// GetItemByHashName is a helper method to define mock.On call
//   - ctx context.Context
//   - hashName string
func (_e *MockRepository_Expecter) GetItemByHashName(ctx interface{}, hashName interface{}) *MockRepository_GetItemByHashName_Call {
	return &MockRepository_GetItemByHashName_Call{Call: _e.mock.On("GetItemByHashName", ctx, hashName)}
}

func (_c *MockRepository_GetItemByHashName_Call) Run(run func(ctx context.Context, hashName string)) *MockRepository_GetItemByHashName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetItemByHashName_Call) Return(getItemByHashNameRow repository.GetItemByHashNameRow, err error) *MockRepository_GetItemByHashName_Call {
	_c.Call.Return(getItemByHashNameRow, err)
	return _c
}

func (_c *MockRepository_GetItemByHashName_Call) RunAndReturn(run func(ctx context.Context, hashName string) (repository.GetItemByHashNameRow, error)) *MockRepository_GetItemByHashName_Call {
	_c.Call.Return(run)
	return _c
}

// GetItemByID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetItemByID(ctx context.Context, ids []int32) ([]repository.Item, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetItemByID")
	}

	var r0 []repository.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int32) ([]repository.Item, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []int32) []repository.Item); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []int32) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetItemByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItemByID'
type MockRepository_GetItemByID_Call struct {
	*mock.Call
}

// GetItemByID is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []int32
func (_e *MockRepository_Expecter) GetItemByID(ctx interface{}, ids interface{}) *MockRepository_GetItemByID_Call {
	return &MockRepository_GetItemByID_Call{Call: _e.mock.On("GetItemByID", ctx, ids)}
}

func (_c *MockRepository_GetItemByID_Call) Run(run func(ctx context.Context, ids []int32)) *MockRepository_GetItemByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []int32
		if args[1] != nil {
			arg1 = args[1].([]int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetItemByID_Call) Return(items []repository.Item, err error) *MockRepository_GetItemByID_Call {
	_c.Call.Return(items, err)
	return _c
}

func (_c *MockRepository_GetItemByID_Call) RunAndReturn(run func(ctx context.Context, ids []int32) ([]repository.Item, error)) *MockRepository_GetItemByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetItems provides a mock function for the type MockRepository
func (_mock *MockRepository) GetItems(ctx context.Context) ([]repository.Item, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetItems")
	}

	var r0 []repository.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]repository.Item, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []repository.Item); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItems'
type MockRepository_GetItems_Call struct {
	*mock.Call
}

// GetItems is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) GetItems(ctx interface{}) *MockRepository_GetItems_Call {
	return &MockRepository_GetItems_Call{Call: _e.mock.On("GetItems", ctx)}
}

func (_c *MockRepository_GetItems_Call) Run(run func(ctx context.Context)) *MockRepository_GetItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_GetItems_Call) Return(items []repository.Item, err error) *MockRepository_GetItems_Call {
	_c.Call.Return(items, err)
	return _c
}

func (_c *MockRepository_GetItems_Call) RunAndReturn(run func(ctx context.Context) ([]repository.Item, error)) *MockRepository_GetItems_Call {
	_c.Call.Return(run)
	return _c
}

// SearchItemsByName provides a mock function for the type MockRepository
func (_mock *MockRepository) SearchItemsByName(ctx context.Context, arg repository.SearchItemsByNameParams) ([]repository.SearchItemsByNameRow, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for SearchItemsByName")
	}

	var r0 []repository.SearchItemsByNameRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.SearchItemsByNameParams) ([]repository.SearchItemsByNameRow, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.SearchItemsByNameParams) []repository.SearchItemsByNameRow); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.SearchItemsByNameRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.SearchItemsByNameParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_SearchItemsByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchItemsByName'
type MockRepository_SearchItemsByName_Call struct {
	*mock.Call
}

// SearchItemsByName is a helper method to define mock.On call
//   - ctx context.Context
//   - arg repository.SearchItemsByNameParams
func (_e *MockRepository_Expecter) SearchItemsByName(ctx interface{}, arg interface{}) *MockRepository_SearchItemsByName_Call {
	return &MockRepository_SearchItemsByName_Call{Call: _e.mock.On("SearchItemsByName", ctx, arg)}
}

func (_c *MockRepository_SearchItemsByName_Call) Run(run func(ctx context.Context, arg repository.SearchItemsByNameParams)) *MockRepository_SearchItemsByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.SearchItemsByNameParams
		if args[1] != nil {
			arg1 = args[1].(repository.SearchItemsByNameParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_SearchItemsByName_Call) Return(searchItemsByNameRows []repository.SearchItemsByNameRow, err error) *MockRepository_SearchItemsByName_Call {
	_c.Call.Return(searchItemsByNameRows, err)
	return _c
}

func (_c *MockRepository_SearchItemsByName_Call) RunAndReturn(run func(ctx context.Context, arg repository.SearchItemsByNameParams) ([]repository.SearchItemsByNameRow, error)) *MockRepository_SearchItemsByName_Call {
	_c.Call.Return(run)
	return _c
}

// SearchItemsCount provides a mock function for the type MockRepository
func (_mock *MockRepository) SearchItemsCount(ctx context.Context, name string) (int64, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for SearchItemsCount")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_SearchItemsCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchItemsCount'
type MockRepository_SearchItemsCount_Call struct {
	*mock.Call
}

// SearchItemsCount is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockRepository_Expecter) SearchItemsCount(ctx interface{}, name interface{}) *MockRepository_SearchItemsCount_Call {
	return &MockRepository_SearchItemsCount_Call{Call: _e.mock.On("SearchItemsCount", ctx, name)}
}

func (_c *MockRepository_SearchItemsCount_Call) Run(run func(ctx context.Context, name string)) *MockRepository_SearchItemsCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_SearchItemsCount_Call) Return(n int64, err error) *MockRepository_SearchItemsCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepository_SearchItemsCount_Call) RunAndReturn(run func(ctx context.Context, name string) (int64, error)) *MockRepository_SearchItemsCount_Call {
	_c.Call.Return(run)
	return _c
}
