// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (
    name,
    hash_name
) VALUES ($1, $2)
ON CONFLICT (hash_name) 
DO UPDATE SET 
    name = EXCLUDED.name,
    updated_at = NOW()
RETURNING id, name, hash_name, created_at, updated_at
`

type CreateItemParams struct {
	Name     string
	HashName string
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem, arg.Name, arg.HashName)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HashName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrGetItem = `-- name: CreateOrGetItem :one
WITH inserted AS (
    INSERT INTO items (name, hash_name) 
    VALUES ($1, $2)
    ON CONFLICT (hash_name) DO NOTHING
    RETURNING id, name, hash_name, created_at, updated_at
)
SELECT id, name, hash_name, created_at, updated_at FROM inserted
UNION ALL
SELECT id, name, hash_name, created_at, updated_at FROM items WHERE hash_name = $2 AND NOT EXISTS (SELECT 1 FROM inserted)
`

type CreateOrGetItemParams struct {
	Name     string
	HashName string
}

type CreateOrGetItemRow struct {
	ID        int32
	Name      string
	HashName  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateOrGetItem(ctx context.Context, arg CreateOrGetItemParams) (CreateOrGetItemRow, error) {
	row := q.db.QueryRow(ctx, createOrGetItem, arg.Name, arg.HashName)
	var i CreateOrGetItemRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HashName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getItemByHashName = `-- name: GetItemByHashName :one
SELECT
    id,
    name,
    hash_name,
    created_at,
    updated_at
FROM items
WHERE hash_name = $1
`

func (q *Queries) GetItemByHashName(ctx context.Context, hashName string) (Item, error) {
	row := q.db.QueryRow(ctx, getItemByHashName, hashName)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HashName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getItems = `-- name: GetItems :many
SELECT
    id,
    name,
    hash_name,
    created_at,
    updated_at
FROM items
`

func (q *Queries) GetItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.Query(ctx, getItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.HashName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
