// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package repository

import (
	"context"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (
    name,
    hash_name
) VALUES ($1, $2)
ON CONFLICT (hash_name) 
DO UPDATE SET 
    name = EXCLUDED.name,
    updated_at = NOW()
RETURNING id, name, hash_name, created_at, updated_at
`

type CreateItemParams struct {
	Name     string
	HashName string
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem, arg.Name, arg.HashName)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HashName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getItemByHashName = `-- name: GetItemByHashName :one
SELECT
    id,
    name,
    hash_name,
    created_at,
    updated_at
FROM items
WHERE hash_name = $1
`

func (q *Queries) GetItemByHashName(ctx context.Context, hashName string) (Item, error) {
	row := q.db.QueryRow(ctx, getItemByHashName, hashName)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HashName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getItemByID = `-- name: GetItemByID :many
SELECT
    id,
    name,
    hash_name,
    created_at,
    updated_at
FROM items
WHERE id = ANY($1::int[])
`

func (q *Queries) GetItemByID(ctx context.Context, ids []int32) ([]Item, error) {
	rows, err := q.db.Query(ctx, getItemByID, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.HashName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItems = `-- name: GetItems :many
SELECT
    id,
    name,
    hash_name,
    created_at,
    updated_at
FROM items
`

func (q *Queries) GetItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.Query(ctx, getItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.HashName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
