// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (
    name,
    icon_url,
    hash_name
) VALUES ($1, $2, $3)
ON CONFLICT (hash_name) 
DO UPDATE SET 
    name = EXCLUDED.name,
    icon_url = EXCLUDED.icon_url,
    updated_at = NOW()
RETURNING id, name, hash_name, created_at, updated_at, icon_url
`

type CreateItemParams struct {
	Name     string
	IconUrl  pgtype.Text
	HashName string
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem, arg.Name, arg.IconUrl, arg.HashName)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HashName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IconUrl,
	)
	return i, err
}

const getAllItemsCount = `-- name: GetAllItemsCount :one
SELECT 
    COUNT(*) as count
FROM items
`

func (q *Queries) GetAllItemsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getAllItemsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getItemByHashName = `-- name: GetItemByHashName :one
SELECT
    id,
    name,
    hash_name,
    created_at,
    updated_at
    icon_url
FROM items
WHERE hash_name = $1
`

type GetItemByHashNameRow struct {
	ID        int32
	Name      string
	HashName  string
	CreatedAt pgtype.Timestamptz
	IconUrl   pgtype.Timestamptz
}

func (q *Queries) GetItemByHashName(ctx context.Context, hashName string) (GetItemByHashNameRow, error) {
	row := q.db.QueryRow(ctx, getItemByHashName, hashName)
	var i GetItemByHashNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HashName,
		&i.CreatedAt,
		&i.IconUrl,
	)
	return i, err
}

const getItemByID = `-- name: GetItemByID :many
SELECT
    id,
    name,
    hash_name,
    created_at,
    updated_at,
    icon_url
FROM items
WHERE id = ANY($1::int[])
`

func (q *Queries) GetItemByID(ctx context.Context, ids []int32) ([]Item, error) {
	rows, err := q.db.Query(ctx, getItemByID, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.HashName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IconUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItems = `-- name: GetItems :many
SELECT
    id,
    name,
    hash_name,
    created_at,
    updated_at,
    icon_url
FROM items
`

func (q *Queries) GetItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.Query(ctx, getItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.HashName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IconUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchItemsByName = `-- name: SearchItemsByName :many
WITH score AS (
    SELECT 
        id,
        name, 
        similarity(name, $3) AS sim_score
    FROM items
)
SELECT 
    id,
    name,
    sim_score
FROM score
WHERE sim_score > 0.1
ORDER BY sim_score DESC
LIMIT $1 OFFSET $2
`

type SearchItemsByNameParams struct {
	Limit  int32
	Offset int32
	Name   string
}

type SearchItemsByNameRow struct {
	ID       int32
	Name     string
	SimScore float32
}

func (q *Queries) SearchItemsByName(ctx context.Context, arg SearchItemsByNameParams) ([]SearchItemsByNameRow, error) {
	rows, err := q.db.Query(ctx, searchItemsByName, arg.Limit, arg.Offset, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchItemsByNameRow
	for rows.Next() {
		var i SearchItemsByNameRow
		if err := rows.Scan(&i.ID, &i.Name, &i.SimScore); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchItemsCount = `-- name: SearchItemsCount :one
WITH score AS (
    SELECT 
        similarity(name, $1) AS sim_score
    FROM items
)
SELECT 
    COUNT(*) as count
FROM score
WHERE sim_score > 0.1
`

func (q *Queries) SearchItemsCount(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, searchItemsCount, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}
