// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Item struct {
	ID        int32
	Name      string
	HashName  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	IconUrl   pgtype.Text
}

type Price struct {
	ID           int64
	ItemID       int32
	SellPrice    int32
	SellListings int32
	CreatedAt    pgtype.Timestamptz
}
