// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package timescale_repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Price struct {
	ID           pgtype.Int8
	ItemID       int32
	SellPrice    int32
	SellListings int32
	Time         pgtype.Timestamptz
	ItemName     pgtype.Text
}

type PriceChanges24h struct {
	Bucket       interface{}
	ItemID       int32
	ItemName     pgtype.Text
	OpenPrice    interface{}
	ClosePrice   interface{}
	SellListings interface{}
	ChangePct    interface{}
}
