// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prices.sql

package timescale_repository

import (
	"context"
)

const insertPrice = `-- name: InsertPrice :exec
INSERT INTO prices (
    item_id,
    sell_price,
    sell_listings
) VALUES ($1, $2, $3)
`

type InsertPriceParams struct {
	ItemID       int32
	SellPrice    int32
	SellListings int32
}

func (q *Queries) InsertPrice(ctx context.Context, arg InsertPriceParams) error {
	_, err := q.db.Exec(ctx, insertPrice, arg.ItemID, arg.SellPrice, arg.SellListings)
	return err
}
